SCHEDULER:
  TEST_NAME: "CLASS-POLLUTION-CODEQL"

  # Path to workspace (base directory for storing results)
  # WORKSPACE/output/ will be created to store the results
  WORKSPACE: "/home/jackfromeast/Desktop/python-class-pollution/tasks/codeql-class-pollution-1K/output"

  # Option: "seed" or "list"
  MODE: "seed"
  REPO_URL: "https://github.com/dgilland/pydash.git"
  REPO_URL_LIST: ""
  URL_LIST_FROM: 0
  URL_LIST_TO: 500

  # Maximum number of workers to run in parallel
  MAX_WORKER: 2

  # Time budget for each worker to analyze each repo
  TIMEOUT_PER_WORKER: 5400

WORKER:
  CODEQL:
    CLI: "/home/jackfromeast/Downloads/codeql/codeql"
    THREADS: 4
    RAM: 4096 # MB
    TIMEOUT: 600 # 10 minutes

  QUERY_MODE: query # query or qlpack
  QUERIES: [
    "/home/jackfromeast/Desktop/python-class-pollution/codeql/codeql-query/class-pollution-all/query/MultiLevelClassPollutionQuery.ql"
  ]

  DELETE_AFTER_QUERY: True # False when debugging
